#####################################################
#
# CREADO POR PEDRO REINA ROJAS (apachebcn@gmail.com)
#
#####################################################


version: '3.9'
services:

  odoo:

    container_name: ${CONTAINER_NAME}
    build:
      context: ./build
      args:
        - MODE=prod
        - ODOO_VERSION=${ODOO_VERSION}
    image: "${CONTAINER_NAME}-image"
    depends_on:
      - odoo-db
    links:
      - odoo-db
    hostname: ${ODOO_HOSTNAME}
    labels:
      # Traefik
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${ODOO_HOST}"
      traefik.port: '8069'
      # Caddy
      caddy: ${ODOO_HOST}
      caddy.reverse_proxy: "{{upstreams 8069}}"
    expose:
      - '80' 
      - '443'
    networks:
      - database
      - web
    volumes:
      - ../volumes/var_run/:/var/run/
      - ../volumes/data/odoo-web-data:/home/odoo/odoo-web-data/
      - ../volumes/addons_me:/home/odoo/odoo-app/addons_me
    tty: true
    restart: always
    command: --log-level=${ODOO_LOG_MODE}
    environment:
      - EXPOSE_PUBLIC_PORT_ODOO=${EXPOSE_PUBLIC_PORT_ODOO}
      - MODE=prod
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - CONTAINER_NAME=${CONTAINER_NAME}


  odoo-db:

    container_name: ${CONTAINER_NAME}-db
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - database
    volumes:
      - ../volumes/var_run/:/var/run/
      - ../volumes/data/db-data:/var/lib/postgresql/data/pgdata
    restart: always


networks:
  web:
    external: true
  database: {}


